name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Dependencies
        run: go install github.com/haya14busa/goverage@latest

      - name: Tests
        run: |
          goverage -race -coverprofile=coverage.txt -covermode=atomic
          make test/units test/bench test/lint

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
